[theme]
base="dark"
primaryColor="#00B3A6"
backgroundColor="#343541"
secondaryBackgroundColor="#202123"
textColor="#E8EAED"
font="sans serif"

[server]
headless=true
port=8501


# Optional: wide layout can be enabled
[browser]
gatherUsageStats=false
